const GET_ALL_GENRES = "GET_ALL_GENRES";
const GET_PLATFORMS = "GET_PLATFORMS"
const POST_GAMES = "POST_GAMES"
const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAMES"
const GET_VIDEOGAME_BY_NAME = "GET_VIDEOGAME_BY_NAME"
const GET_VIDEOGAME_BY_ID = "GET_VIDEOGAME_BY_ID"
const CLEAR_DETAIL = "CLEAR_DETAIL"

const SORT_NAME_ASCENDING_ORDER = "SORT_NAME_ASCENDING_ORDER"
const SORT_NAME_DESCENDING_ORDER ="SORT_NAME_DESCENDING_ORDER"
const SORT_RATING_ASCENDING_ORDER = "SORT_RATING_ASCENDING_ORDER"
const SORT_RATING_DESCENDING_ORDER = "SORT_RATING_DESCENDING_ORDER"
const NO_SORT = "NO_SORT"
export {
    NO_SORT,
    SORT_RATING_DESCENDING_ORDER,
    SORT_RATING_ASCENDING_ORDER,
    SORT_NAME_DESCENDING_ORDER, 
    SORT_NAME_ASCENDING_ORDER, 
    CLEAR_DETAIL,
    GET_VIDEOGAME_BY_ID,
    GET_ALL_VIDEOGAMES,
    GET_ALL_GENRES,
    GET_PLATFORMS, 
    POST_GAMES, 
    GET_VIDEOGAME_BY_NAME}